language: python
python:
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - docker build -t jenkinstest .
  - docker stop jenkinstest
  - docker rm jenkinstest
  - docker run -it -d --name=jenkinstest jenkinstest
  - docker exec jenkinstest python preprocess.py
  - docker exec jenkinstest python training.py