version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t jenkinstest .
      - run: docker stop jenkinstest || true
      - run: docker rm jenkinstest || true
      - run: docker run -it -d --name=jenkinstest jenkinstest
      - run: docker exec jenkinstest python preprocess.py
      - run: docker exec jenkinstest python training.py