version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: yes | docker image prune
      - run: docker build -t jtdocker .
      - run: docker run --rm --name=jtdocker jtdocker