version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker image prune --force
      - run: docker build -t jtdocker .
      - run: docker run --rm --name=jtdocker jtdocker